mosquitto:
  broker: mqtt.clearstreamer.com
  port: '443'
  client_id: zenserver-xxx-poller
  username: ${MQTT_USERNAME:-your-mqtt-user}
  password: ${MQTT_PASSWORD:-changeme}
  topic: s3
  qos: 2
  tls:
    enabled: true
mount:
  path: /mnt/unionfs/xxx/
  inclusions:
  - /mnt/unionfs/xxx/
  exclusions:
  - '**/lost+found/**'
  - '**/*.nfo'
  - '**/*.jpg'
rclone:
  enabled: true
  host: 127.0.0.1
  port: '5585'
  remote: zendrive-xxx
autoscan-servers:
- host: 127.0.0.1
  port: 3031
  username: plexuser
  password: ${AUTOSCAN_PASSWORD:-changeme}
  inclusions:
  - /mnt/unionfs/xxx/
  exclusions:
  - /mnt/unionfs/downloads/
  - /mnt/unionfs/transcodes/
- host: 127.0.0.1
  port: 3030
  username: plexuser
  password: ${AUTOSCAN_PASSWORD:-changeme}
  inclusions:
  - /mnt/unionfs/xxx/
  exclusions:
  - /mnt/unionfs/downloads/
  - /mnt/unionfs/transcodes/
  - /mnt/unionfs/.recyclebin/
  - /mnt/unionfs/.downloads/
  - /mnt/unionfs/.inbound/
paths:
  feeder_paths:
  - source: /media/zen-ceph/xxx/
    target: /mnt/unionfs/xxx/
database:
  path: /state/zenlocalpoller-xxx.db
  retention: 72h
poller:
  delay: 30s
  poll-interval: 30s
  retries: 5
log:
  level: info
